### ISSUE TITLE
[FEATURE REQUEST] New normalisation functions

### ISSUE THREAD

**Issue by 4theKnowledge** [nlp-tlp/mudlark#10]
It would be desirable if these normalisation functions could be considered for integration into the `simple_normalise` function. I have provided some attempts at them which can be used or improved upon.

**Removing undesirable characters**
This function would remove characters that are superfluous, not semantically or syntactically relevant to the text, which may have been erroneously added.

```python
import regex

chars_to_keep = "\,&\.\#\@\/-"
fnc_rmv_chars = lambda tex: regex.sub(rf"[^a-zA-Z0-9 {chars_to_keep}]", " ", text)
```

**Removing duplicate contiguous characters, e.g. "##", "@@@", etc.**
Duplicate characters are often used as markers in technical user-generated text to gain attention by authors but are not semantically relevant to the text itself. Moreover, they may introduce issues in dictionary-based normalisations downstream.

```python
import regex

fnc_rmv_dupe_chars = lambda text: regex.sub(rf"([{chars_to_keep}])\1+", r"\1", text)
```

**Add space between brackets**
This is useful for segmenting tokens for token-level tagging activities such as information extraction. For example, "(blown)" to "( blown )". Note: This could be extended to other brackets like [],{}, etc, as required in cases like this "engine wont start.[low air]"

```python
text = text.replace("(", "( ")replace(")", " )")
```

**Add space around punctuation (generally)**
This is useful for segmenting tokens for token-level tagging activities such as information extraction. For example, "engine wont start.[low air]" which should be "engine wont start . [low air]".

```python
text = text.replace('.', ' . ')
```

**Comment by LisonLau** [comment]
Changes made are under **simple_normalisation** branch
**Removing undesirable characters**
- Implemented `remove_undesirable_chars` function which removes undesirable characters except:
`chars_to_keep = "\,&\.\#\@\/-"`

**Removing duplicate contiguous characters**
- Implemented `remove_duplicate_contiguous_chars` function which removes duplicates for the following characters:
`chars_to_remove = r"!\"#$%&'()\*\+,-./:;<=>\?@[\\\]^_`{|}~"`

**Add space between brackets**
- This is implemented in the same function below

**Add space around punctuation (generally)**
- Implemented `add_space_around_punctuation` function to add spaces around punctuations - this includes slashes, hypens, brackets, etc.
- Removed existing functions that overlap such as `add_space_around_hyphen` and `space_around_slash`
