### ISSUE TITLE
[ISSUE] `_correct_typos` sort by correction length.

### ISSUE THREAD

**Issue by 4theKnowledge** [nlp-tlp/mudlark#12]
It would be desirable if the `_correct_typos` function sorted corrections by length in descending order to replace longer phrases first.

**Comment by JadeynFeng** [comment]
27/5 update: 

- _correct_typos function sorted by descending order implemented under **simple_normalisation** branch. Sorting occurs within the function, for it to apply to any user-inputted corrections dictionary as well.
